# Ansible Playbook to create a Provider in NAUTOBOT
# Note: you need to export NAUTOBOT_URL and NAUTOBOT_TOKEN first Example:
# export NAUTOBOT_URL=https://192.168.1.1/
# export NAUTOBOT_token=abcde123456723456!!

- name: "Test Nautobot modules"
  connection: local
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Create provider within Nautobot
      networktocode.nautobot.provider:
        url: "{{ lookup('env', 'NAUTOBOT_URL') }}"
        token: "{{ lookup('env', 'NAUTOBOT_TOKEN') }}"
        validate_certs: no
        name: Vaioni
        state: present

    - name: Update provider with other fields
      networktocode.nautobot.provider:
        url: "{{ lookup('env', 'NAUTOBOT_URL') }}"
        token: "{{ lookup('env', 'NAUTOBOT_TOKEN') }}"
        validate_certs: no
        name: Vaioni
        asn: 65001
        account: 200129104
        portal_url: http://vaioni.com
        noc_contact: support@vaioni.com
        admin_contact: admin@vaioni.com
        comments: "Created using Ansible Playbook"
        state: present
...
