# Ansible Playbook to create cables in NAUTOBOT
# Note: you need to export NAUTOBOT_URL and NAUTOBOT_TOKEN first Example:
# export NAUTOBOT_URL=https://192.168.1.1/
# export NAUTOBOT_token=abcde123456723456!!

- name: "Add cables to Nautobot"
  connection: local
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Create cable within Nautobot
      networktocode.nautobot.cable:
        url: "{{ lookup('env', 'NAUTOBOT_URL') }}"
        token: "{{ lookup('env', 'NAUTOBOT_TOKEN') }}"
        validate_certs: no
        termination_a_type: dcim.interface
        termination_a:
          device: lab-sw1
          name: GigabitEthernet 0/0
        termination_b_type: dcim.interface
        termination_b:
          device: lab-mgmt-switch
          name: GigabitEthernet 0/1
        status: Connected
        state: present
...
