- name: "Add location to Nautobot"
  connection: local
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create location in Nautobot
      networktocode.nautobot.location:
        url: "{{ lookup('env', 'NAUTOBOT_URL') }}"
        token: "{{ lookup('env', 'NAUTOBOT_TOKEN') }}"
        validate_certs: no
        name: Autobot-lab
        status: Active
        location_type:
          name: Home-lab
        state: present
...
