# Ansible Playbook to create a device type in NAUTOBOT
# Note: you need to export NAUTOBOT_URL and NAUTOBOT_TOKEN first Example:
# export NAUTOBOT_URL=https://192.168.1.1/
# export NAUTOBOT_token=abcde123456723456!!

- name: "Test Nautobot modules"
  connection: local
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Create a device type within Nautobot
      networktocode.nautobot.device_type:
        url: "{{ lookup('env', 'NAUTOBOT_URL') }}"
        token: "{{ lookup('env', 'NAUTOBOT_TOKEN') }}"
        validate_certs: no
        model: C9300X-48
        manufacturer: Cisco
        part_number: C9300X-48HX
        u_height: 1
        is_full_depth: True
        subdevice_role: parent
        state: present
