# Ansible Playbook to create a role in NAUTOBOT
# Note: you need to export NAUTOBOT_URL and NAUTOBOT_TOKEN first Example:
# export NAUTOBOT_URL=https://192.168.1.1/
# export NAUTOBOT_token=abcde123456723456!!

- name: "Add a role to Nautobot"
  connection: local
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Create role within Nautobot
      networktocode.nautobot.role:
        url: "{{ lookup('env', 'NAUTOBOT_URL') }}"
        token: "{{ lookup('env', 'NAUTOBOT_TOKEN') }}"
        validate_certs: no
        name: Core Switch
        color: FFFFFF
        content_types:
          - "dcim.device"
        state: present
...
