# Ansible Playbook to create a device in NAUTOBOT
# Note: you need to export NAUTOBOT_URL and NAUTOBOT_TOKEN first Example:
# export NAUTOBOT_URL=https://192.168.1.1/
# export NAUTOBOT_token=abcde123456723456!!

- name: "Add a device to Nautobot"
  connection: local
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Create a device within Nautobot
      networktocode.nautobot.device:
        url: "{{ lookup('env', 'NAUTOBOT_URL') }}"
        token: "{{ lookup('env', 'NAUTOBOT_TOKEN') }}"
        validate_certs: no
        name: Test Device
        device_type: C9300X-48
        role: Core Switch
        location: Nautobot-lab
        status: Active
        state: present
...
